{"uid":"84e6ce1e4901bec1","name":"test_validate_payment[api-19]","fullName":"tests.endpoints.test_payments#test_validate_payment","historyId":"5dad880742ddfd39d1015f29f76581bb","time":{"start":1733062502778,"stop":1733062510702,"duration":7924},"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.ApiClient.ApiClient object at 0x7f1abd1935c0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.dict(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.ApiClient.ApiClient object at 0x7f1abd1935c0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.dict(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1733062449933,"stop":1733062449934,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"base_url","time":{"start":1733062502778,"stop":1733062502778,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"api_client","time":{"start":1733062502778,"stop":1733062502778,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.ApiClient.ApiClient object at 0x7f1abd1935c0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.dict(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.ApiClient.ApiClient object at 0x7f1abd1935c0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.dict(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...401e-842e-fbcdb7ecb853'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","steps":[],"attachments":[{"uid":"59442df2d132aa03","name":"log","source":"59442df2d132aa03.txt","type":"text/plain","size":5212},{"uid":"a90816abe513859a","name":"stdout","source":"a90816abe513859a.txt","type":"text/plain","size":461},{"uid":"13470a40813afdb9","name":"stderr","source":"13470a40813afdb9.txt","type":"text/plain","size":57068}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Duplicate item in order"},{"name":"feature","value":"Orders API"},{"name":"parentSuite","value":"tests.endpoints"},{"name":"suite","value":"test_payments"},{"name":"host","value":"fv-az915-185"},{"name":"thread","value":"2322-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.endpoints.test_payments"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"x_task_value","value":"'api-19'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"84e6ce1e4901bec1.json","parameterValues":["'api-19'"]}