{"uid":"4af2c648f37167bc","name":"test_validate_payment[api-19]","fullName":"tests.endpoints.test_payments#test_validate_payment","historyId":"5dad880742ddfd39d1015f29f76581bb","time":{"start":1733084331231,"stop":1733084336139,"duration":4908},"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f11d8fe49e0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.api_client.ApiClient object at 0x7f11d8fe49e0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1733084316291,"stop":1733084316293,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1733084316293,"stop":1733084316293,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_test","time":{"start":1733084316293,"stop":1733084318605,"duration":2312},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"worker_id","time":{"start":1733084316293,"stop":1733084316293,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_client","time":{"start":1733084316293,"stop":1733084316293,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f11d8fe49e0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.api_client.ApiClient object at 0x7f11d8fe49e0>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...49c9-ad75-a5f063f6052a'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","steps":[],"attachments":[{"uid":"7c07e6a065ce53da","name":"log","source":"7c07e6a065ce53da.txt","type":"text/plain","size":5174},{"uid":"96d53dd32d38fdf1","name":"stdout","source":"96d53dd32d38fdf1.txt","type":"text/plain","size":461},{"uid":"86e1d83b9e535dad","name":"stderr","source":"86e1d83b9e535dad.txt","type":"text/plain","size":5138}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"setup_test::0","time":{"start":1733084336144,"stop":1733084336145,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Orders API"},{"name":"story","value":"Duplicate item in order"},{"name":"parentSuite","value":"tests.endpoints"},{"name":"suite","value":"test_payments"},{"name":"host","value":"fv-az1245-950"},{"name":"thread","value":"2630-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.endpoints.test_payments"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"x_task_value","value":"'api-19'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"4af2c648f37167bc.json","parameterValues":["'api-19'"]}